### ISSUE TITLE
TypeError: Class constructor ApplicationClient cannot be invoked without 'new'

### ISSUE THREAD

**Issue by MrJackdaw** [algorand-devrel/beaker-ts#22]
Hello all,

First, thanks for the hard work on Beaker and Beaker-ts. 

I used the `npx beaker generate` command to generate a TS client from an `application.json` file (also generated by beaker via the recently-released Algokit). Seems odd, because I am instantiating it with `new SimpleEscrow({ ... })`

Any advice/help would be appreciated!

### Error output:
```
export class SimpleEscrow extends bkr.ApplicationClient {
^
TypeError: Class constructor ApplicationClient cannot be invoked without 'new'
    at new SimpleEscrow (/[REDACTED]/algokit-projects/toastducks/simpleescrow/simpleescrow_client.ts:3:1)
    at main (/[REDACTED]/algokit-projects/toastducks/index.ts:18:18)
    at Object.<anonymous> (/[REDACTED]/algokit-projects/toastducks/index.ts:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module.m._compile (/[REDACTED]/algokit-projects/toastducks/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Object.require.extensions.<computed> [as .ts] (/[REDACTED]/algokit-projects/toastducks/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Function.Module._load (node:internal/modules/cjs/loader:935:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)
[nodemon] app crashed - waiting for file changes before starting...
```

### client file: 

```typescript
import algosdk from "algosdk";
import * as bkr from "beaker-ts";
export class SimpleEscrow extends bkr.ApplicationClient {
    desc: string = "";
    override appSchema: bkr.Schema = { declared: { amount: { type: bkr.AVMType.uint64, key: "amount", desc: "", static: false }, receiver: { type: bkr.AVMType.bytes, key: "receiver", desc: "", static: false } }, reserved: {} };
    override acctSchema: bkr.Schema = { declared: {}, reserved: {} };
    override approvalProgram: string = "[ TRUNCATED ]";
    override clearProgram: string = "I3ByYWdtYSB2ZXJzaW9uIDgKcHVzaGludCAwIC8vIDAKcmV0dXJu";
    override methods: algosdk.ABIMethod[] = [
        new algosdk.ABIMethod({ name: "configure_escrow", desc: "", args: [{ type: "uint64", name: "amount", desc: "" }, { type: "string", name: "receiver", desc: "" }, { type: "pay", name: "deposit", desc: "" }], returns: { type: "void", desc: "" } }),
        new algosdk.ABIMethod({ name: "withdraw", desc: "", args: [], returns: { type: "void", desc: "" } })
    ];
    async configure_escrow(args: {
        amount: bigint;
        receiver: string;
        deposit: algosdk.TransactionWithSigner | algosdk.Transaction;
    }, txnParams?: bkr.TransactionOverrides): Promise<bkr.ABIResult<void>> {
        const result = await this.execute(await this.compose.configure_escrow({ amount: args.amount, receiver: args.receiver, deposit: args.deposit }, txnParams));
        return new bkr.ABIResult<void>(result);
    }
    async withdraw(txnParams?: bkr.TransactionOverrides): Promise<bkr.ABIResult<void>> {
        const result = await this.execute(await this.compose.withdraw(txnParams));
        return new bkr.ABIResult<void>(result);
    }
    compose = {
        configure_escrow: async (args: {
            amount: bigint;
            receiver: string;
            deposit: algosdk.TransactionWithSigner | algosdk.Transaction;
        }, txnParams?: bkr.TransactionOverrides, atc?: algosdk.AtomicTransactionComposer): Promise<algosdk.AtomicTransactionComposer> => {
            return this.addMethodCall(algosdk.getMethodByName(this.methods, "configure_escrow"), { amount: args.amount, receiver: args.receiver, deposit: args.deposit }, txnParams, atc);
        },
        withdraw: async (txnParams?: bkr.TransactionOverrides, atc?: algosdk.AtomicTransactionComposer): Promise<algosdk.AtomicTransactionComposer> => {
            return this.addMethodCall(algosdk.getMethodByName(this.methods, "withdraw"), {}, txnParams, atc);
        }
    };
}
```

**Comment by barnjamin** [comment]
I think this ended up being an issue with algosdk version installed, try upping it to version v2.0

**Comment by MrJackdaw** [comment]
Thanks for the response. I actually did have `algosdk@2.0.0` installed. But I performed some due-diligence, because there was the possibility of an algosdk conflict with another dependency. 

So I aliased `algosdk@latest` to `algosdk-edge`, then updated and re-ran my script [I'm working in a cli]. I updated the import in the generated client file:
```
import algosdk from "algosdk-edge";
```
But still got the same error ☹️

**Comment by barnjamin** [comment]
what version of beaker-ts is it? maybe up that as well?

**Comment by MrJackdaw** [comment]
> what version of beaker-ts is it? maybe up that as well?

I got this from `npm i -s beaker-ts`:

```
"beaker-ts": "^0.0.70"
```

which resolves to `"version": "0.0.70"` in **package-lock**. Is that an older version?

**Comment by barnjamin** [comment]
What does your tsconfig look like? 

check out https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne

**Comment by MrJackdaw** [comment]
> What does your tsconfig look like?
> 
> check out https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne

Once again, you saved the day. I checked that link, changed my target to `es6`, and got further than before. I didn't remove references to ES2015, though I'll consider it if something else crops up. 

Going to post the full tsconfig file in case newbies need it. 
Cheers again @barnjamin!

### Tsconfig.json
```json
{
  "compilerOptions": {
    "allowJs": true,
    "declaration": true,
    "downlevelIteration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "lib": ["es5", "dom", "es2015", "es2015.collection"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmit": false,
    "resolveJsonModule": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "outDir": "./lib/",
    "sourceMap": false,
    "strict": true,
    "target": "es6",
    "useDefineForClassFields": true
  },
  "include": ["./**/*.ts"],
  "exclude": ["node_modules", "/lib", "./src/**/*.test.*"]
}
```
[ As usual, you can please close this or lock/leave for posterity ]
